# Generated by Django 4.2.16 on 2024-10-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('titulo', models.CharField(help_text='Titulo del post', max_length=80, primary_key=True, serialize=False, unique=True)),
                ('contenido', models.CharField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('miniatura', models.ImageField(blank=True, upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.categorias')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.sexo')),
            ],
        ),
    ]
