# Generated by Django 4.2.16 on 2024-10-10 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_carritoitem_agregado_en_carritoitem_session_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.carrito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='agregado_en',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='usuario',
        ),
    ]
